# Base de datos en la nube
spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:54548/railway
spring.datasource.username=root
spring.datasource.password=DMuOcxJWiEKaBMRcidDPIXigeVcLHaPW

# Propiedades de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update